providers:
  google:
    display_name: "Google"
    icon: "ðŸ”µ"
    color: "#4285F4"
    auth_url: "https://accounts.google.com/o/oauth2/v2/auth"
    token_url: "https://oauth2.googleapis.com/token"
    web:
      client_id: "${GOOGLE_WEB_CLIENT_ID}"
      client_secret: "${GOOGLE_WEB_CLIENT_SECRET}"
      redirect_uri: "http://localhost:8081/auth/callback/google"
      scopes:
        - email
        - profile
        - openid
        - https://www.googleapis.com/auth/gmail.readonly
        - https://www.googleapis.com/auth/gmail.send
    mobile:
      client_id: "${GOOGLE_MOBILE_CLIENT_ID}"
      redirect_uri: "area.app:/auth"
      scopes:
        - email
        - profile
        - openid
        - https://www.googleapis.com/auth/gmail.readonly
        - https://www.googleapis.com/auth/gmail.send

  microsoft:
    display_name: "Microsoft"
    icon: "ðŸŸ¦"
    color: "#00A4EF"
    auth_url: "https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize"
    token_url: "https://login.microsoftonline.com/consumers/oauth2/v2.0/token"
    web:
      client_id: "${MICROSOFT_WEB_CLIENT_ID}"
      client_secret: "${MICROSOFT_WEB_CLIENT_SECRET}"
      redirect_uri: "http://localhost:8081/auth/callback/microsoft"
      scopes:
        - openid
        - profile
        - email
        - User.Read
        - Mail.Read
        - Mail.Send
    mobile:
      client_id: "${MICROSOFT_MOBILE_CLIENT_ID}"
      redirect_uri: "area.app:/auth"
      scopes:
        - openid
        - profile
        - email
        - User.Read
        - Mail.Read
        - Mail.Send

  github:
    display_name: "GitHub"
    icon: "âš«"
    color: "#24292e"
    auth_url: "https://github.com/login/oauth/authorize"
    token_url: "https://github.com/login/oauth/access_token"
    web:
      client_id: "${GITHUB_WEB_CLIENT_ID}"
      client_secret: "${GITHUB_WEB_CLIENT_SECRET}"
      redirect_uri: "http://localhost:8081/auth/callback/github"
      scopes:
        - user
        - user:email
        - read:user
    mobile:
      client_id: "${GITHUB_MOBILE_CLIENT_ID}"
      client_secret: "${GITHUB_MOBILE_CLIENT_SECRET}"
      redirect_uri: "area.app:/auth"
      scopes:
        - user
        - user:email
        - read:user
