providers:
  google:
    display_name: "Google"
    icon: "ðŸ”µ"
    color: "#4285F4"
    auth_url: "https://accounts.google.com/o/oauth2/v2/auth"
    token_url: "https://oauth2.googleapis.com/token"
    web:
      client_id: "${GOOGLE_WEB_CLIENT_ID}"
      client_secret: "${GOOGLE_WEB_CLIENT_SECRET}"
      redirect_uri: "http://localhost:8081/auth/callback/google"
      scopes:
        - email
        - profile
        - openid
        - https://www.googleapis.com/auth/gmail.readonly
        - https://www.googleapis.com/auth/gmail.send
    mobile:
      client_id: "${GOOGLE_MOBILE_CLIENT_ID}"
      redirect_uri: "area.app:/auth"
      scopes:
        - email
        - profile
        - openid
        - https://www.googleapis.com/auth/gmail.readonly
        - https://www.googleapis.com/auth/gmail.send

  microsoft:
    display_name: "Microsoft"
    icon: "ðŸŸ¦"
    color: "#00A4EF"
    auth_url: "https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize"
    token_url: "https://login.microsoftonline.com/consumers/oauth2/v2.0/token"
    web:
      client_id: "${MICROSOFT_WEB_CLIENT_ID}"
      client_secret: "${MICROSOFT_WEB_CLIENT_SECRET}"
      redirect_uri: "http://localhost:8081/auth/callback/microsoft"
      scopes:
        - openid
        - profile
        - email
        - User.Read
        - Mail.Read
        - Mail.Send
    mobile:
      client_id: "${MICROSOFT_MOBILE_CLIENT_ID}"
      redirect_uri: "area.app:/auth"
      scopes:
        - openid
        - profile
        - email
        - User.Read
        - Mail.Read
        - Mail.Send

  github:
    display_name: "GitHub"
    icon: "âš«"
    color: "#24292e"
    auth_url: "https://github.com/login/oauth/authorize"
    token_url: "https://github.com/login/oauth/access_token"
    web:
      client_id: "${GITHUB_WEB_CLIENT_ID}"
      client_secret: "${GITHUB_WEB_CLIENT_SECRET}"
      redirect_uri: "http://localhost:8081/auth/callback/github"
      # ADD MORE SCOPES IF NECESSARY (https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps)
      scopes:
        - user
        - user:email
        - read:user
        - admin:repo_hook
        - read:repo_hook
        - write:repo_hook
        - repo
    mobile:
      client_id: "${GITHUB_MOBILE_CLIENT_ID}"
      client_secret: "${GITHUB_MOBILE_CLIENT_SECRET}"
      redirect_uri: "area.app:/auth"
      scopes:
        - user
        - user:email
        - read:user
        - admin:repo_hook
        - read:repo_hook
        - write:repo_hook
        - repo

  spotify:
    display_name: "Spotify"
    icon: "ðŸŸ¢"
    color: "#1DB954"
    auth_url: "https://accounts.spotify.com/authorize"
    token_url: "https://accounts.spotify.com/api/token"
    web:
      client_id: "${SPOTIFY_CLIENT_ID}"
      client_secret: "${SPOTIFY_CLIENT_SECRET}"
      redirect_uri: "http://127.0.0.1:8081/auth/callback/spotify"
      scopes:
        - user-read-email
        - user-read-private
        - playlist-read-private
        - playlist-modify-public
        - playlist-modify-private
    mobile:
      client_id: "${SPOTIFY_MOBILE_CLIENT_ID}"
      client_secret: "${SPOTIFY_MOBILE_CLIENT_SECRET}"
      redirect_uri: "area.app:/auth"
      scopes:
        - user-read-email
        - user-read-private
        - playlist-read-private
        - playlist-modify-public
        - playlist-modify-private
  trello:
    display_name: "Trello"
    icon: "ðŸ›‚"
    color: "#0079BF"
    auth_url: "https://trello.com/1/authorize"
    token_url: "https://trello.com/1/OAuthGetAccessToken"
    web:
      client_id: "${TRELLO_WEB_CLIENT_API_KEY}"
      client_secret: "${TRELLO_WEB_CLIENT_API_SECRET}"
      redirect_uri: "http://localhost:8081/auth/callback/trello"
      scopes:
        - read
        - write
        - account
    mobile:
      client_id: "${TRELLO_WEB_CLIENT_API_KEY}"
      client_secret: "${TRELLO_WEB_CLIENT_API_SECRET}"
      redirect_uri: "area.app:/auth"
      scopes:
        - read
        - write
        - account
