providers:
  google:
    web:
      client_id: "${GOOGLE_WEB_CLIENT_ID}"
      client_secret: "${GOOGLE_WEB_CLIENT_SECRET}"
      redirect_uri: "http://localhost:8081/auth/callback/google"
      scopes:
        - email
        - profile
        - openid
        - https://www.googleapis.com/auth/gmail.readonly
        - https://www.googleapis.com/auth/gmail.send
    mobile:
      client_id: "${GOOGLE_MOBILE_CLIENT_ID}"
      redirect_uri: "area.app:/auth"
      scopes:
        - email
        - profile
        - openid
        - https://www.googleapis.com/auth/gmail.readonly
        - https://www.googleapis.com/auth/gmail.send
