providers:
  google:
    display_name: "Google"
    icon: "ðŸ”µ"
    color: "#4285F4"
    auth_url: "https://accounts.google.com/o/oauth2/v2/auth"
    token_url: "https://oauth2.googleapis.com/token"
    web:
      client_id: "${GOOGLE_WEB_CLIENT_ID}"
      client_secret: "${GOOGLE_WEB_CLIENT_SECRET}"
      redirect_uri: "http://localhost:8081/auth/callback/google"
      scopes:
        - email
        - profile
        - openid
        - https://www.googleapis.com/auth/gmail.readonly
        - https://www.googleapis.com/auth/gmail.send
    mobile:
      client_id: "${GOOGLE_MOBILE_CLIENT_ID}"
      redirect_uri: "area.app:/auth"
      scopes:
        - email
        - profile
        - openid
        - https://www.googleapis.com/auth/gmail.readonly
        - https://www.googleapis.com/auth/gmail.send
