services:
  backend:
    image: area-fastapi
    env_file: ".env"
    ports:
      - "8080:80"
    depends_on:
      - db
    # volumes:
    #   - ./user_images:/user_images
    #   - ./event_images:/event_images
    #   - ./news_images:/news_images
    #   - ./startup_uploads:/startup_uploads

  db:
    image: postgres
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8123:8080"
    # restart: always
    depends_on:
      - db

  client_mobile:
    build: ./mobile
    volumes:
      - ./mobile/apk:/apk
  
  client_web:
    build: ./Front/AREAA
    ports:
      - "8081:80"
    volumes:
      - ./mobile/apk/client.apk:/usr/share/nginx/html/client.apk:ro
    depends_on:
      - db
      - client_mobile

volumes:
  pgdata:
  # user_images:
  # event_images:
  # news_images:
  # startup_uploads:
