services:
  backend:
    image: area-fastapi
    environment:
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1440348984823775334/Lm5MvF1-EvXfvHcWBjtlKUnc2vhZhxQ3WfIBwdpKOJeTziz1oTe5_n-G6h25OV9E5h3Q
    env_file: ".env"
    ports:
      - "80:80"
    depends_on:
      - db
    # volumes:
    #   - ./user_images:/user_images
    #   - ./event_images:/event_images
    #   - ./news_images:/news_images
    #   - ./startup_uploads:/startup_uploads

  db:
    image: postgres
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    # restart: always
    depends_on:
      - db
  
  client_web:
    build: ./Front/AREAA
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  pgdata:
  # user_images:
  # event_images:
  # news_images:
  # startup_uploads:
